name: daily Build
on:
 push:
   branches: [ main ]
 schedule:
   - cron: '0 0 * * *'
 workflow_dispatch:      

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10.12'
         
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         
     - name: Update
       run: python update.py

     - name: Commit and push if changed
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add -f data/
         git add -f calendar/
         git commit -m "Update data" || exit 0
         git push